# Generated by Django 6.0.3 on 2026-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_academico',
            field=models.EmailField(help_text='Example: aluno@edu.df.senac.br', max_length=150, verbose_name='E-mail Acadêmico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Completo'),
        ),
    ]
