# Generated by Django 6.0.3 on 2026-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=6, unique=True, verbose_name='Nº Patrimônio')),
                ('marca', models.CharField(choices=[('Acer', 'Acer'), ('DELL', 'Dell'), ('APPLE', 'Apple'), ('VAIO', 'Vaio'), ('AVELL', 'Avell'), ('ALIENWARE', 'Alienware'), ('Samsung', 'Samsung'), ('HP', 'HP'), ('ASUS', 'Asus')], max_length=20)),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('CINZA', 'Cinza'), ('BRANCO', 'Branco'), ('PRATA', 'Prata')], max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Manutenção'), ('EMPRESTADO', 'Emprestado')], default='DISPONIVEL', max_length=15)),
            ],
        ),
    ]
