# Generated by Django 6.0.3 on 2026-03-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=6, unique=True, verbose_name='Nº Patrimônio')),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('CINZA', 'Cinza'), ('BRANCO', 'Branco'), ('PRATA', 'Prata')], max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Manutenção'), ('EMPRESTADO', 'Emprestado')], default='DISPONIVEL', max_length=15)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand')),
            ],
            options={
                'verbose_name': 'Notebook',
            },
        ),
    ]
