# Generated by Django 6.0.3 on 2026-03-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'verbose_name': 'Notebook'},
        ),
    ]
