# Generated by Django 6.0.3 on 2026-03-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carregador', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.notebook', verbose_name='Notebook')),
            ],
        ),
    ]
