# Generated by Django 6.0.3 on 2026-03-13 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brand_options_alter_notebook_options'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name': 'Empréstimo'},
        ),
        migrations.AlterField(
            model_name='loans',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.notebook', verbose_name='Notebook'),
        ),
    ]
